language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - pip install --upgrade setuptools pip
install:
  - pip install -e .
  - pip install -r test-requirements.txt
script:
  - mypy --config-file=.mypy.ini featurefilter
  - pylama featurefilter tests
  - pytest --cov featurefilter
after_success:
  - coveralls
before_deploy:
  - rm -rf build/
  - rm -rf dist/
  - rm -rf *.egg-info/
deploy:
  provider: pypi
  user: floscha
  password:
    secure: I2NpeIiqvc1Ggb2weEkV9Rbzl8xSwkdnBCeCwKMolJQkbFNqrWXT652mwo/SFp4CtzcyA7hawxxziZyzUWYUgbvTp5Bu7gGdtguf72s0wrniuR8oYqdxXeq8A+VTHdlyNuToCj2bz45TREWa+vw54oMMCocdl0k9+/ZgNMj0TsP+09fTdg9MFmYFL3GuwpcOjojvbzhWZyqvHX7XEjNukJQ64bi6HIKIeN1DbnoXevGTdyakHeuNJ2Kyx18qnlLh1cQ1fB/kdeG+2uuh33OSDJwNjK13/NO65DjoKoRqqF75H3c4MrUsX32BVNNFney4jfyyq3CHMGg1rOPd9SwEZLBIIA4W9LI6rYpJbUtll+pi7x2+VN047Ivvv00qPJobNhqUvRk8mPaFAEsmhOJNzqxrns6OmAOCsP3HLlmgVnv5Zxdx5x8QX9Hx4X/qebvC9mcwnRfXrfe+xcolSRF79Hcq+voroysvO4UIaDHBozqj2l3VBrQm+gcmJwk9jFtmzvrZUUXx9KC8n1DNyBO8C3UXfrOksOYeHZSrdHMsIpDGqtTqr5YOevUUUhX3+uHbhA1LcI9DW4gVAM1QxQ1ouWIUMyel2h/5AJx9uFrzInl+o3cH5VvNzVrMr9T5opBCkRnBAIlVrnaUwPB1Jhzy/qxQ1/4GAOtPmBgxcgS3zNQ=
  on:
    tags: true
