language: python
matrix:
  include:
    - python: 3.5
      env:
        - SPARK_VERSION=2.3.3
        - PANDAS_VERSION=0.23.4
        - PYARROW_VERSION=0.10.0
    - python: 3.6
      env:
        - SPARK_VERSION=2.4.3
        - PANDAS_VERSION=0.24.2
        - PYARROW_VERSION=0.10.0
    - python: 3.7
      dist: xenial
      sudo: true
      jdk:
        - oraclejdk8
      env:
        - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
        - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
        - SPARK_VERSION=2.4.3
        - PANDAS_VERSION=0.24.2
        - PYARROW_VERSION=0.13.0
before_install:
  - pip install --upgrade setuptools pip
install:
  - pip install -e .[spark]
  - pip install -r test-requirements.txt
script:
  - mypy --config-file=.mypy.ini featurefilter
  - pylama featurefilter tests
  - pytest --cov featurefilter
after_success:
  - coveralls
before_deploy:
  - rm -rf build/
  - rm -rf dist/
  - rm -rf *.egg-info/
deploy:
  provider: pypi
  user: floscha
  password:
    secure: KQCF1jyWgFGeaIersUPEReU7nh+8uKTvN6MCutx7rcLMjBsGDUUF7CVW0WT/sSG+B5TT1nfSt7yfBalwpfv8L+HQ05QFArase2LzqnapevropR1Agt/tO1wCw4Ox3OhkuWhhg8zU75/s3dxhsoG3PO+t86YdyADw1tnDiDUyvptAz5z1nS8JOzfcRINaUJUpk2iKztBPJhqhqUEwx+zTAQu0d+58vqGLMWVv+xGAGkIbJMixdQVrBow3W21wAPMfVHA+WCdAh83gGEdNVByTjRnR9so2t/XY0F113kSRboqfh63HpwES3LnNkLyCvMz7uN+/KOD9FsdL4CSKG6ws5HiwZnM5mo4n5fKovZw33437Kv1Y5quPr+RaBnrmLDTBt1yNaDghA/lZrzXKv8JdOYFGYJXIfdw4EFTFOHwDMYQu0XvF6nKOJaSNB+ZqSEAF8Je13jFluDawJOnfoeK64i2EoFFLt810mqMJo6x0t8gh2vZsM8QguojJE87AYBmPTp6kWMbwV/UZ16R1tFHF/55HkdCX78E26JStyunQuygc+bOgasatW9Sweuh33l7uprn0joxKhTUcsAffVToeKns6e+T4rReKNxsKgPsaeH4mD3uUbbXxN2MRgmQqeMn94n0XQCS8pWFGslhE/mhMN5cICyUV+LHSDFWmOcSm4Q4=
  on:
    tags: true
  skip_existing: true
